GET  http://localhost:3000/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzU5MTU5NDE5LCJleHAiOjE3NTkxNjMwMTl9.waNs_4aoO6giq6m0Bq6DD6Oph8WoOkDjLc2iyC7uHc4
